### ISSUE TITLE
Failed when parsing struct

### ISSUE THREAD

**Issue by januwA** [13xforever/gvas-converter#6]
```
>GvasConverter.exe "SaveData1.sav"
Parsing UE4 save file structure...
792
Unhandled exception. System.FormatException: Offset: 0x00000359. Expected struct ID 00000000-0000-0000-0000-000000000000, but was 70ca6bd1-ca33-4dc9-a297-844e7cc2096e
   at GvasFormat.Serialization.UETypes.UEStructProperty.Read(BinaryReader reader, Int64 valueLength) in C:\Users\ajanuw\Desktop\gvas-converter-master\GvasFormat\Serialization\UETypes\UEStructProperty.cs:line 15
   at GvasFormat.Serialization.UESerializer.Deserialize(String name, String type, Int64 valueLength, BinaryReader reader) in C:\Users\ajanuw\Desktop\gvas-converter-master\GvasFormat\Serialization\UESerializer.UETypes.cs:line 35
   at GvasFormat.Serialization.UETypes.UEProperty.Read(BinaryReader reader) in C:\Users\ajanuw\Desktop\gvas-converter-master\GvasFormat\Serialization\UETypes\UEProperty.cs:line 27
   at GvasFormat.Serialization.UESerializer.Read(Stream stream) in C:\Users\ajanuw\Desktop\gvas-converter-master\GvasFormat\Serialization\UESerializer.cs:line 32
   at GvasConverter.Program.Main(String[] args) in C:\Users\ajanuw\Desktop\gvas-converter-master\GvasConverter\Program.cs:line 30
```

![image](https://user-images.githubusercontent.com/22570563/125074448-dfb63d00-e0ef-11eb-86c4-732295a70f8e.png)

![image](https://user-images.githubusercontent.com/22570563/125143796-6a2d8980-e14e-11eb-9709-133fbb1f3655.png)

**Comment by januwA** [comment]
I pulled a new [branch](https://github.com/januwA/gvas-converter) and fixed some errors in Debug mode
